#!/bin/bash

sleep 15

grep max_connect_errors /var/vcap/jobs/pxc-mysql/config/my.cnf

if [ $? -eq 0 ]; then
  sed -i 's/max-connect-errors =.*/max-connect-errors = 456/' /var/vcap/jobs/pxc-mysql/config/my.cnf
else
  echo "[mysqld]" >> /var/vcap/jobs/pxc-mysql/config/my.cnf
  echo "max-connect-errors = 456" >> /var/vcap/jobs/pxc-mysql/config/my.cnf
fi



exit 0
