// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/galera-healthcheck/sequence_number"
)

type FakeSequenceNumberChecker struct {
	CheckStub        func() (string, error)
	checkMutex       sync.RWMutex
	checkArgsForCall []struct{}
	checkReturns     struct {
		result1 string
		result2 error
	}
}

func (fake *FakeSequenceNumberChecker) Check() (string, error) {
	fake.checkMutex.Lock()
	fake.checkArgsForCall = append(fake.checkArgsForCall, struct{}{})
	fake.checkMutex.Unlock()
	if fake.CheckStub != nil {
		return fake.CheckStub()
	} else {
		return fake.checkReturns.result1, fake.checkReturns.result2
	}
}

func (fake *FakeSequenceNumberChecker) CheckCallCount() int {
	fake.checkMutex.RLock()
	defer fake.checkMutex.RUnlock()
	return len(fake.checkArgsForCall)
}

func (fake *FakeSequenceNumberChecker) CheckReturns(result1 string, result2 error) {
	fake.CheckStub = nil
	fake.checkReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ sequence_number.SequenceNumberChecker = new(FakeSequenceNumberChecker)
