---
name: ((deployment_name))

releases:
- name: "pxc"
  version: "0.44.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/pxc-release?v=0.44.0"
  sha1: "495099d35e3b2a24bf73ed42c152e1ff10cb3576"
- name: "bpm"
  version: "1.1.18"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.18"
  sha1: "86675f90d66f7018c57f4ae0312f1b3834dd58c9"

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: mysql
  instances: 3
  azs: [z1, z2, z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: pxc-mysql
    release: pxc
    properties:
      admin_password: ((cf_mysql_mysql_admin_password))
      engine_config:
        galera:
          enabled: true
      remote_admin_access: true
      tls:
        galera: ((galera_server_certificate))
        server: ((mysql_server_certificate))
      seeded_databases:
      - name: upgrade_data
        username: test-user
        password: integration-tests
  - name: bootstrap
    release: pxc
  - name: cluster-health-logger
    release: pxc
    properties:
      db_password: ((cf_mysql_mysql_cluster_health_password))
  - name: galera-agent
    release: pxc
    properties:
      endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
      db_password: ((cf_mysql_mysql_galera_healthcheck_db_password))
  - name: gra-log-purger
    release: pxc
  - name: smoke-tests
    release: pxc
    properties:
      db_password: ((smoke_tests_db_password))
  - name: smoke-tests-user
    release: pxc
- name: proxy
  instances: 2
  azs: [z1, z2]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: proxy
    release: pxc
    provides:
      proxy:
        as: proxy
        shared: true
    properties:
      api_password: ((cf_mysql_proxy_api_password))

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: false

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: pxc_galera_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_galera_ca
- name: pxc_server_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_server_ca
- name: galera_server_certificate
  type: certificate
  options:
    ca: pxc_galera_ca
    extended_key_usage: [ "server_auth", "client_auth" ]
    common_name: galera_server_certificate
- name: mysql_server_certificate
  type: certificate
  options:
    ca: pxc_server_ca
    common_name: mysql_server_certificate
- name: smoke_tests_db_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_db_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
