// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/mariadb_ctrl/mariadb_helper/seeder"
	_ "github.com/go-sql-driver/mysql"
)

type FakeSeeder struct {
	CreateDBIfNeededStub        func() error
	createDBIfNeededMutex       sync.RWMutex
	createDBIfNeededArgsForCall []struct{}
	createDBIfNeededReturns struct {
		result1 error
	}
	IsExistingUserStub        func() (bool, error)
	isExistingUserMutex       sync.RWMutex
	isExistingUserArgsForCall []struct{}
	isExistingUserReturns struct {
		result1 bool
		result2 error
	}
	CreateUserStub        func() error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct{}
	createUserReturns struct {
		result1 error
	}
	GrantUserAllPrivilegesStub        func() error
	grantUserAllPrivilegesMutex       sync.RWMutex
	grantUserAllPrivilegesArgsForCall []struct{}
	grantUserAllPrivilegesReturns struct {
		result1 error
	}
}

func (fake *FakeSeeder) CreateDBIfNeeded() error {
	fake.createDBIfNeededMutex.Lock()
	fake.createDBIfNeededArgsForCall = append(fake.createDBIfNeededArgsForCall, struct{}{})
	fake.createDBIfNeededMutex.Unlock()
	if fake.CreateDBIfNeededStub != nil {
		return fake.CreateDBIfNeededStub()
	} else {
		return fake.createDBIfNeededReturns.result1
	}
}

func (fake *FakeSeeder) CreateDBIfNeededCallCount() int {
	fake.createDBIfNeededMutex.RLock()
	defer fake.createDBIfNeededMutex.RUnlock()
	return len(fake.createDBIfNeededArgsForCall)
}

func (fake *FakeSeeder) CreateDBIfNeededReturns(result1 error) {
	fake.CreateDBIfNeededStub = nil
	fake.createDBIfNeededReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSeeder) IsExistingUser() (bool, error) {
	fake.isExistingUserMutex.Lock()
	fake.isExistingUserArgsForCall = append(fake.isExistingUserArgsForCall, struct{}{})
	fake.isExistingUserMutex.Unlock()
	if fake.IsExistingUserStub != nil {
		return fake.IsExistingUserStub()
	} else {
		return fake.isExistingUserReturns.result1, fake.isExistingUserReturns.result2
	}
}

func (fake *FakeSeeder) IsExistingUserCallCount() int {
	fake.isExistingUserMutex.RLock()
	defer fake.isExistingUserMutex.RUnlock()
	return len(fake.isExistingUserArgsForCall)
}

func (fake *FakeSeeder) IsExistingUserReturns(result1 bool, result2 error) {
	fake.IsExistingUserStub = nil
	fake.isExistingUserReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeSeeder) CreateUser() error {
	fake.createUserMutex.Lock()
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct{}{})
	fake.createUserMutex.Unlock()
	if fake.CreateUserStub != nil {
		return fake.CreateUserStub()
	} else {
		return fake.createUserReturns.result1
	}
}

func (fake *FakeSeeder) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeSeeder) CreateUserReturns(result1 error) {
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSeeder) GrantUserAllPrivileges() error {
	fake.grantUserAllPrivilegesMutex.Lock()
	fake.grantUserAllPrivilegesArgsForCall = append(fake.grantUserAllPrivilegesArgsForCall, struct{}{})
	fake.grantUserAllPrivilegesMutex.Unlock()
	if fake.GrantUserAllPrivilegesStub != nil {
		return fake.GrantUserAllPrivilegesStub()
	} else {
		return fake.grantUserAllPrivilegesReturns.result1
	}
}

func (fake *FakeSeeder) GrantUserAllPrivilegesCallCount() int {
	fake.grantUserAllPrivilegesMutex.RLock()
	defer fake.grantUserAllPrivilegesMutex.RUnlock()
	return len(fake.grantUserAllPrivilegesArgsForCall)
}

func (fake *FakeSeeder) GrantUserAllPrivilegesReturns(result1 error) {
	fake.GrantUserAllPrivilegesStub = nil
	fake.grantUserAllPrivilegesReturns = struct {
		result1 error
	}{result1}
}

var _ seeder.Seeder = new(FakeSeeder)
