#!/bin/bash

set -o errexit -o nounset -o pipefail

: "${BOSH_VAR_azs:='[z1,z2,z3]'}"
: "${BOSH_VAR_network:=default}"
: "${BOSH_VAR_vm_type:=default}"
: "${PXC_DEPLOYMENT_NAME:=pxc}"
: "${PXC_DEPLOY_VERSION:=}"
: "${MYSQL_VERSION:=}"
: "${ENABLE_CLUSTER:=true}"
: "${ENABLE_INTEGRATION:=true}"
: "${REDACT:=false}"

main() {
  local deployment_name=${PXC_DEPLOYMENT_NAME}
  local -a deploy_opts=(
    --ops-file=operations/deployment-name.yml
    --var=deployment_name="${deployment_name}"
  )

  if [[ -n ${PXC_DEPLOY_VERSION} ]]; then
    deploy_opts+=(
      --ops-file=operations/pxc-version.yml
      --var=pxc_version="${PXC_DEPLOY_VERSION}"
    )
  else
    deploy_opts+=(--ops-file=operations/dev-release.yml)
  fi

  if [[ -n ${MYSQL_VERSION} ]]; then
    deploy_opts+=(
      --ops-file=operations/mysql-version.yml
      --var=mysql_version="'${MYSQL_VERSION}'"
    )
  fi

  if [[ ${ENABLE_CLUSTER} == "true" ]]; then
    deploy_opts+=(
      --ops-file=operations/use-clustered.yml
      --ops-file=operations/iaas/cluster.yml
    )
  else
    deploy_opts+=(--ops-file=operations/iaas/single-node.yml)
  fi

  if [[ "${REDACT}" == "false" ]]; then
    deploy_opts+=("--no-redact")
  fi

  deploy_opts+=("$@")

  bosh deploy pxc-deployment.yml \
    --deployment="${deployment_name}" \
    --non-interactive \
    --vars-env=BOSH_VAR \
    "${deploy_opts[@]}"
}

main "$@"
