#!/bin/bash

set -exuo pipefail

cluster_options=(
    --ops-file operations/use-clustered.yml
)

integration_options=(
    --ops-file operations/integration-tests.yml
)

function deploy() {
    local no_redact="--"
    if [[ "${REDACT:-"false"}" != "true" ]]; then
        no_redact="--no-redact"
    fi
    bosh -d "${PXC_DEPLOYMENT_NAME:-pxc}" -n deploy "$@" "${no_redact}"
}

if [[ ${ENABLE_CLUSTER:-"true"} == "true" ]]
then
    deploy_options+=("${cluster_options[@]}")
fi

if [[ ${ENABLE_INTEGRATION:-"false"} == "true" ]]
then
    deploy_options+=("${integration_options[@]}")
fi
deploy pxc-deployment.yml "${deploy_options[@]}"
