#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  local deployment_name=${PXC_DEPLOYMENT_NAME:-pxc}
  local -a deploy_opts=(
    --ops-file=operations/deployment-name.yml
    --var=deployment_name="${deployment_name}"
  )

  if [[ -z "${PXC_RELEASE-}" ]]; then
    deploy_opts+=(--ops-file=operations/dev-release.yml)
  else
    deploy_opts+=(--ops-file=operations/pxc-version.yml)
    deploy_opts+=(--var=pxc_version=${PXC_RELEASE})
  fi

  if [[ -n ${MYSQL_VERSION:-} ]]; then
    deploy_opts+=(
      --ops-file=operations/mysql-version.yml
      --var=mysql_version="'${MYSQL_VERSION}'"
    )
  fi

  if [[ ${ENABLE_CLUSTER:-true} == "true" ]]; then
    deploy_opts+=(--ops-file=operations/use-clustered.yml)
  fi

  if [[ ${ENABLE_INTEGRATION:-true} == "true" ]]; then
    deploy_opts+=(--ops-file=operations/integration-tests.yml)
  fi

  if [[ "${REDACT:-}" == "false" ]]; then
    deploy_opts+=("--no-redact")
  fi

  deploy_opts+=("$@")

  bosh deploy pxc-deployment.yml \
    --deployment="${deployment_name}" \
    --non-interactive \
    "${deploy_opts[@]}"
}

main "$@"
