#!/usr/bin/env bash

set -eux

echo -e "\n>>>>>>>> Running Unit Tests Script for PXC release..."
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

source "${RELEASE_DIR}/.envrc"

echo -e "\n>>>>>>>> Testing our bash scripts fatally..."
# TODO: port over a download logs script for pxc #157104900
#shellcheck --shell=bash "${RELEASE_DIR}/scripts/download-logs"

go get github.com/maxbrunsfeld/counterfeiter

echo -e "\n>>>>>>>> Testing Switchboard..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/switchboard/bin/test" "$@"

echo -e "\n>>>>>>>> Testing Galera Healthcheck..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/galera-healthcheck/bin/test" "$@"

echo -e "\n>>>>>>>> Testing Galera Init..."
"${RELEASE_DIR}/src/github.com/cloudfoundry/galera-init/bin/test-unit" "$@"

echo -e "\n>>>>>>>> Testing Bootstrapper..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-bootstrap/bin/test" "$@"

echo -e "\n>>>>>>>> Testing Cluster Health Logger..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-cluster-health-logger/bin/test" "$@"

echo -e "\n>>>>>>>> Testing Migrate To PXC..."
pushd "${RELEASE_DIR}/src/migrate-to-pxc"
  ./bin/test "$@"
popd

pushd ${RELEASE_DIR}/spec
  bundle install
  bundle exec rspec ./
popd
