#!/usr/bin/env bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

source "${RELEASE_DIR}/.envrc"

echo -e "\n>>>>>>>> Testing Galera Init Integration..."
"${RELEASE_DIR}/src/github.com/cloudfoundry/galera-init/bin/test-integration" "$@"
