// This file was generated by counterfeiter
package upgraderfakes

import (
	"sync"

	"github.com/cloudfoundry/mariadb_ctrl/upgrader"
)

type FakeUpgrader struct {
	UpgradeStub        func() error
	upgradeMutex       sync.RWMutex
	upgradeArgsForCall []struct{}
	upgradeReturns     struct {
		result1 error
	}
	NeedsUpgradeStub        func() (bool, error)
	needsUpgradeMutex       sync.RWMutex
	needsUpgradeArgsForCall []struct{}
	needsUpgradeReturns     struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUpgrader) Upgrade() error {
	fake.upgradeMutex.Lock()
	fake.upgradeArgsForCall = append(fake.upgradeArgsForCall, struct{}{})
	fake.recordInvocation("Upgrade", []interface{}{})
	fake.upgradeMutex.Unlock()
	if fake.UpgradeStub != nil {
		return fake.UpgradeStub()
	} else {
		return fake.upgradeReturns.result1
	}
}

func (fake *FakeUpgrader) UpgradeCallCount() int {
	fake.upgradeMutex.RLock()
	defer fake.upgradeMutex.RUnlock()
	return len(fake.upgradeArgsForCall)
}

func (fake *FakeUpgrader) UpgradeReturns(result1 error) {
	fake.UpgradeStub = nil
	fake.upgradeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUpgrader) NeedsUpgrade() (bool, error) {
	fake.needsUpgradeMutex.Lock()
	fake.needsUpgradeArgsForCall = append(fake.needsUpgradeArgsForCall, struct{}{})
	fake.recordInvocation("NeedsUpgrade", []interface{}{})
	fake.needsUpgradeMutex.Unlock()
	if fake.NeedsUpgradeStub != nil {
		return fake.NeedsUpgradeStub()
	} else {
		return fake.needsUpgradeReturns.result1, fake.needsUpgradeReturns.result2
	}
}

func (fake *FakeUpgrader) NeedsUpgradeCallCount() int {
	fake.needsUpgradeMutex.RLock()
	defer fake.needsUpgradeMutex.RUnlock()
	return len(fake.needsUpgradeArgsForCall)
}

func (fake *FakeUpgrader) NeedsUpgradeReturns(result1 bool, result2 error) {
	fake.NeedsUpgradeStub = nil
	fake.needsUpgradeReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeUpgrader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.upgradeMutex.RLock()
	defer fake.upgradeMutex.RUnlock()
	fake.needsUpgradeMutex.RLock()
	defer fake.needsUpgradeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeUpgrader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ upgrader.Upgrader = new(FakeUpgrader)
