on:
  pull_request:

jobs:
  run-go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - run: cd src/generate-auto-tune-mysql; go test; cd ../..
