name: Automated PR unit tests
run-name: 'unit tests: PR #${{ github.event.number }} "${{ github.event.pull_request.title }}"'

on:
  pull_request

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pxc-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ oldstable, stable ]
    name: go "${{ matrix.version }}" version
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache-dependency-path: "**/*.sum"
      - uses: actions/setup-ruby@v1
      - run: go version
      - run: scripts/test-unit
